version: 2.1

commands:
  setup-remote-docker:
    steps:
      - setup_remote_docker:
          version: 19.03.13

executors:
  docker:
    docker:
      - image: docker:19.03.13-git

jobs:
  build-docker-image:
    executor: docker
    steps:
      - checkout
      - setup-remote-docker
      - run: docker build --target builder -t builder .
  publish-docker-image:
    executor: docker
    environment:
      IMAGE_TAG: ghcr.io/robertograham/departure-app:latest
    steps:
      - checkout
      - setup-remote-docker
      - run: |
          docker login ghcr.io -u RobertoGraham -p $PERSONAL_ACCESS_TOKEN
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
  run-tests:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/robertograham/departure-tests:latest
  run-terraform-job:
    docker:
      - image: curlimages/curl:7.74.0
    parameters:
      job:
        type: enum
        enum: [ "plan", "apply" ]
    steps:
      - run: |
          curl -sSfX POST \
          -o /dev/null \
          -d '{"branch":"master","parameters":{"application":"departure-api","commit-hash":"'"$CIRCLE_SHA1"'","job":"<< parameters.job >>"}}' \
          -H "Content-Type:application/json" \
          -H "Circle-Token:$CIRCLE_TOKEN" \
          https://circleci.com/api/v2/project/gh/RobertoGraham/departure-infra/pipeline

workflows:
  release:
    jobs:
      - build-docker-image:
          filters:
            branches:
              ignore: master
      - run-terraform-job:
          job: plan
          filters:
            branches:
              ignore: master
      - publish-docker-image:
          filters:
            branches:
              only: master
      - run-tests:
          requires:
            - publish-docker-image
      - run-terraform-job:
          job: apply
          requires:
            - run-tests