version: 2.0
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: alpine:3.10.2
    steps:
      - run:
          command: |
            apk --no-cache add curl
            curl -sSfX PATCH \
            -o /dev/null \
            -d '{"DEPARTURE_APP_COMMIT_HASH":"'"$CIRCLE_SHA1"'"}' \
            -H "Content-Type:application/json" \
            -H "Authorization:Bearer $HEROKU_API_KEY" \
            -H "Accept:application/vnd.heroku+json; version=3" \
            https://api.heroku.com/apps/departure-infra-backend/config-vars