const BUS_STOP_DEPARTURES_REQUESTED = "BUS_STOP_DEPARTURES_REQUESTED";
const BUS_STOP_DEPARTURES_RECEIVED = "BUS_STOP_DEPARTURES_RECEIVED";
const BUS_STOP_DEPARTURES_ERROR = "BUS_STOP_DEPARTURES_ERROR";

export {
  BUS_STOP_DEPARTURES_REQUESTED,
  BUS_STOP_DEPARTURES_RECEIVED,
  BUS_STOP_DEPARTURES_ERROR
};
