const BUS_STOPS_REQUESTED = "BUS_STOPS_REQUESTED";
const BUS_STOP_REQUESTED = "BUS_STOP_REQUESTED";
const BUS_STOPS_RECEIVED = "BUS_STOPS_RECEIVED";
const BUS_STOP_RECEIVED = "BUS_STOP_RECEIVED";
const BUS_STOPS_ERROR = "BUS_STOPS_ERROR";
const BUS_STOP_ERROR = "BUS_STOP_ERROR";

export {
  BUS_STOPS_REQUESTED,
  BUS_STOP_REQUESTED,
  BUS_STOPS_RECEIVED,
  BUS_STOP_RECEIVED,
  BUS_STOPS_ERROR,
  BUS_STOP_ERROR
};
